In [28]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [29]:
PATH = './data'
manuel = PATH + '/codeBook_v3.csv'
kp2020 = PATH + '/KP2020.csv'
kp2021 = PATH + '/KP2021.csv'
npa2020 = PATH + '/NPA2020.csv'

In [30]:
npa2020 = pd.read_csv(npa2020, encoding='cp949')
kp2021 = pd.read_csv(kp2021, encoding='cp949')
kp2020 = pd.read_csv(kp2020, encoding='cp949')

In [49]:
list(npa2020.columns)

['RECV_CPLT_DT',
 'RECV_CPLT_TM',
 'NPA_CL',
 'EVT_STAT_CD',
 'EVT_CL_CD',
 'RPTER_SEX',
 'HPPN_OLD_ADDR',
 'HPPN_X',
 'HPPN_Y',
 'SME_EVT_YN']

In [48]:
new_columns = [list(npa2020.columns)[1], list(npa2020.columns)[0]] + list(npa2020.columns)[2:]
new_columns

['RECV_CPLT_TM',
 'RECV_CPLT_DT',
 'NPA_CL',
 'EVT_STAT_CD',
 'EVT_CL_CD',
 'RPTER_SEX',
 'HPPN_OLD_ADDR',
 'HPPN_X',
 'HPPN_Y',
 'SME_EVT_YN']

In [50]:
npa2020[new_columns]

,RECV_CPLT_TM,RECV_CPLT_DT,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,7,20200101,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y
1,132,20200101,13,10,501,1,대전광역시 중구 대흥동(대흥동) 499-1,127.421295,36.325575,NaN
2,39,20200101,13,10,501,1,NaN,127.404663,36.341685,NaN
3,110,20200101,13,10,601,3,NaN,0.000000,0.000000,NaN
4,342,20200101,13,10,601,1,NaN,127.404663,36.341685,NaN
...,...,...,...,...,...,...,...,...,...,...
1178239,3505,20201122,19,10,501,1,,NaN,NaN,
1178240,5213,20201122,13,10,601,,,127.404663,36.341685,
1178241,4627,20201122,19,10,601,1,,NaN,NaN,Y
1178242,5246,20201122,19,5,301,1,충청남도 보령시 신흑동(행정:대천5동),126.516040,36.305619,
1178243,1134,20201122,13,10,601,,,127.404663,36.341685,

In [51]:
kp2020

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN
...,...,...,...,...,...,...,...,...,...,...
77072,충남청,20/12/31 01:18:16.000000000,19,10,302,2.0,충청남도 보령시 주교면 주교리(행정:주교면) 191-6,126.571002,36.387791,NaN
77073,충남청,20/12/31 01:17:45.000000000,19,10,501,3.0,NaN,NaN,NaN,NaN
77074,충남청,20/12/31 00:13:50.000000000,19,10,604,3.0,충청남도 아산시 온천동(행정:온양1동) 1498,127.000391,36.788411,NaN
77075,대전청,20/12/31 00:49:29.000000000,13,10,302,2.0,대전광역시 서구 갈마동(행정:갈마2동) 975,127.373351,36.348051,Y
77076,대전청,20/12/31 00:49:06.000000000,13,10,601,3.0,NaN,NaN,NaN,NaN

In [52]:
kp2021

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,대전청,21/03/07 00:00:01.000000000,13,10,604,3.0,대전광역시 서구 둔산동 1122,127.373676,36.350975,Y
1,대전청,21/03/07 00:02:13.000000000,13,10,201,1.0,대전광역시 유성구 상대동(원신흥동) 469-9,127.339018,36.347420,NaN
2,대전청,21/03/07 00:00:33.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
3,대전청,21/03/07 00:01:18.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
4,대전청,21/03/07 00:01:43.000000000,13,10,308,1.0,대전광역시 중구 선화동 141-16,127.420455,36.330413,NaN
...,...,...,...,...,...,...,...,...,...,...
2594055,대전청,23/01/12 11:23:09.000000000,13,10,104,1.0,대전광역시 유성구 봉명동 (행정:원신흥동 ) 1016-7,127.344600,36.352272,NaN
2594056,충남청,23/01/16 11:59:47.000000000,19,10,307,2.0,충청남도 서산시 음암면 부장리(음암면 ) 560-4,126.514047,36.785626,NaN
2594057,충남청,23/01/16 11:58:54.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2594058,충남청,23/01/14 01:00:47.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2594059,대전청,23/01/14 01:22:31.000000000,13,10,606,1.0,NaN,127.404663,36.341685,NaN

In [ ]:
no_time = pd.concat(kp2020[])

In [55]:
kp2020.iloc[2,:]

RECV_DEPT_NM                             대전청
RECV_CPLT_DM     20/12/01 02:06:52.000000000
NPA_CL                                    13
EVT_STAT_CD                               10
EVT_CL_CD                                601
RPTER_SEX                                1.0
HPPN_PNU_ADDR                            NaN
HPPN_X                            127.404663
HPPN_Y                             36.341685
SME_EVT_YN                               NaN
Name: 2, dtype: object