In [4]:
from PyKakao import Local
LOCAL = Local(service_key = "b2b4d096044642add00262c75e4a6006")
LOCAL.geo_coord2address(127.386345, 36.346855, dataframe=True)['address'][0]

{'address_name': '대전 서구 탄방동 1447-1',
 'region_1depth_name': '대전',
 'region_2depth_name': '서구',
 'region_3depth_name': '탄방동',
 'mountain_yn': 'N',
 'main_address_no': '1447',
 'sub_address_no': '1',
 'zip_code': ''}

In [9]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [13]:
kp_acc = pd.read_csv('./data/kp_acc.csv')
npa_acc = pd.read_csv('./data/npa_acc.csv')

In [12]:
kp_acc.loc[kp_acc['HPPN_PNU_ADDR'] == 0]

Empty DataFrame
Columns: [RECV_DEPT_NM, RECV_CPLT_DM, NPA_CL, EVT_STAT_CD, EVT_CL_CD, RPTER_SEX, HPPN_PNU_ADDR, HPPN_X, HPPN_Y]
Index: []

In [14]:
npa_acc.loc[npa_acc['HPPN_OLD_ADDR'] == 0]

Empty DataFrame
Columns: [RECV_CPLT_DM, NPA_CL, EVT_STAT_CD, EVT_CL_CD, RPTER_SEX, HPPN_OLD_ADDR, HPPN_X, HPPN_Y]
Index: []

In [16]:
kp_acc

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y
0,충남청,1606778270,19,10,401,2,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826717
1,대전청,1606760666,13,10,406,1,대전광역시 유성구 봉명동(행정:온천1동) 575,127.341550,36.353695
2,충남청,1606775838,19,10,402,1,충청남도 천안시 서북구 성환읍 성월리(행정:성환읍) 150,127.136140,36.917900
3,대전청,1606774124,13,10,401,1,대전광역시 중구 석교동(석교동) 85-14,127.447550,36.306725
4,대전청,1606774160,13,10,401,2,대전광역시 중구 석교동(행정:석교동) 88-11,127.447174,36.306694
...,...,...,...,...,...,...,...,...,...
285751,대전청,1673780499,13,10,401,1,대전 서구 괴정동 88-6,127.384285,36.334507
285752,충남청,1673872016,19,10,401,1,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262390,36.751470
285753,충남청,1673625768,19,10,403,2,충청남도 천안시 동남구 다가동 (일봉동 ) 61-35,127.147675,36.789124
285754,대전청,1673685338,13,10,401,1,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433784,36.450726
285755,대전청,1673712800,13,10,401,1,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428280,36.425404