In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
VOICE_CATEGORY = [215]
ACC_CATEGORY = [401,402,403,406]
PATH = './data'
manuel = PATH + '/codeBook_v3.csv'
kp2020_path = PATH + '/KP2020.csv'
kp2021_path = PATH + '/KP2021.csv'
npa2020_path = PATH + '/NPA2020.csv'

In [3]:
npa2020 = pd.read_csv(npa2020_path, encoding='cp949')
kp2021 = pd.read_csv(kp2021_path, encoding='cp949')
kp2020 = pd.read_csv(kp2020_path, encoding='cp949')

In [4]:
npa2020

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,20200101,7,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y
1,20200101,132,13,10,501,1,대전광역시 중구 대흥동(대흥동) 499-1,127.421295,36.325575,NaN
2,20200101,39,13,10,501,1,NaN,127.404663,36.341685,NaN
3,20200101,110,13,10,601,3,NaN,0.000000,0.000000,NaN
4,20200101,342,13,10,601,1,NaN,127.404663,36.341685,NaN
...,...,...,...,...,...,...,...,...,...,...
1178239,20201122,3505,19,10,501,1,,NaN,NaN,
1178240,20201122,5213,13,10,601,,,127.404663,36.341685,
1178241,20201122,4627,19,10,601,1,,NaN,NaN,Y
1178242,20201122,5246,19,5,301,1,충청남도 보령시 신흑동(행정:대천5동),126.516040,36.305619,
1178243,20201122,1134,13,10,601,,,127.404663,36.341685,

In [5]:
from datetime import datetime
def get_unix(df):
    year = df['RECV_CPLT_DT'][2:4]
    month = df['RECV_CPLT_DT'][4:6]
    day = df['RECV_CPLT_DT'][6:]
    time = df['RECV_CPLT_TM'].zfill(6)
    time_format = year + '/' + month + '/' + day + ' ' + time[:2] + ':' + time[2:4] + ':' + time[4:6]
    unix = datetime.strptime(time_format,"%y/%m/%d %H:%M:%S").timestamp()
    return unix

In [6]:
npa2020['RECV_CPLT_DT'] = npa2020['RECV_CPLT_DT'].astype(str)
npa2020['RECV_CPLT_TM'] = npa2020['RECV_CPLT_TM'].astype(str)

In [7]:
npa2020['RECV_CPLT_DM'] = npa2020.apply(get_unix,axis=1)

In [8]:
npa2020.dtypes

RECV_CPLT_DT      object
RECV_CPLT_TM      object
NPA_CL             int64
EVT_STAT_CD        int64
EVT_CL_CD          int64
RPTER_SEX         object
HPPN_OLD_ADDR     object
HPPN_X           float64
HPPN_Y           float64
SME_EVT_YN        object
RECV_CPLT_DM     float64
dtype: object

In [9]:
npa2020.isnull().sum()

RECV_CPLT_DT          0
RECV_CPLT_TM          0
NPA_CL                0
EVT_STAT_CD           0
EVT_CL_CD             0
RPTER_SEX             0
HPPN_OLD_ADDR    258593
HPPN_X           101653
HPPN_Y           101653
SME_EVT_YN       596801
RECV_CPLT_DM          0
dtype: int64

In [10]:
for colum in npa2020.columns:
    print(npa2020[colum].unique(), end='\n\n')

['20200101' '20200102' '20200103' '20200104' '20200105' '20200106'
 '20200107' '20200108' '20200109' '20200110' '20200111' '20200112'
 '20200113' '20200114' '20200115' '20200116' '20200117' '20200118'
 '20200119' '20200120' '20200121' '20200122' '20200123' '20200124'
 '20200125' '20200126' '20200127' '20200128' '20200129' '20200130'
 '20200131' '20200201' '20200202' '20200203' '20200204' '20200205'
 '20200206' '20200208' '20200207' '20200211' '20200209' '20200210'
 '20200311' '20200312' '20200313' '20200314' '20200315' '20200307'
 '20200308' '20200309' '20200310' '20200316' '20200317' '20200212'
 '20200213' '20200214' '20200215' '20200216' '20200217' '20200218'
 '20200223' '20200224' '20200225' '20200226' '20200227' '20200219'
 '20200220' '20200221' '20200222' '20200228' '20200229' '20200301'
 '20200302' '20200303' '20200304' '20200305' '20200306' '20200528'
 '20200529' '20200530' '20200531' '20200525' '20200526' '20200527'
 '20200601' '20200602' '20200413' '20200414' '20200415' '20200416'
 '20200417' '20200409' '20200410' '20200411' '20200412' '20200418'
 '20200419' '20200403' '20200404' '20200405' '20200406' '20200407'
 '20200329' '20200330' '20200331' '20200401' '20200402' '20200408'
 '20200503' '20200504' '20200505' '20200506' '20200429' '20200430'
 '20200501' '20200502' '20200507' '20200508' '20200423' '20200424'
 '20200425' '20200426' '20200427' '20200420' '20200421' '20200422'
 '20200428' '20200324' '20200325' '20200326' '20200327' '20200319'
 '20200320' '20200321' '20200322' '20200323' '20200328' '20200512'
 '20200513' '20200514' '20200515' '20200516' '20200509' '20200510'
 '20200511' '20200517' '20200519' '20200520' '20200521' '20200522'
 '20200523' '20200318' '20200518' '20200524' '20200606' '20200607'
 '20200608' '20200609' '20200603' '20200604' '20200605' '20200610'
 '20200617' '20200611' '20200613' '20200612' '20200615' '20200614'
 '20200616' '20200804' '20200805' '20200806' '20200715' '20200716'
 '20200717' '20200718' '20200710' '20200711' '20200712' '20200713'
 '20200714' '20200719' '20200619' '20200620' '20200621' '20200618'
 '20200622' '20200706' '20200707' '20200708' '20200709' '20200701'
 '20200702' '20200703' '20200704' '20200705' '20200724' '20200725'
 '20200726' '20200720' '20200721' '20200722' '20200723' '20200727'
 '20200627' '20200628' '20200629' '20200630' '20200623' '20200624'
 '20200625' '20200626' '20200801' '20200802' '20200803' '20200728'
 '20200729' '20200730' '20200731' '20200807' '20200808' '20200809'
 '20200810' '20200811' '20200813' '20200812' '20200814' '20200815'
 '20200816' '20200818' '20200817' '20200820' '20200819' '20200821'
 '20200823' '20200822' '20200825' '20200824' '20200826' '20200827'
 '20200828' '20200829' '20200830' '20200831' '20200901' '20200902'
 '20200903' '20200904' '20200905' '20200906' '20200907' '20200908'
 '20200910' '20200909' '20200911' '20200912' '20200913' '20200914'
 '20200915' '20200916' '20200917' '20200918' '20200919' '20200920'
 '20200921' '20200922' '20200923' '20200924' '20200925' '20200926'
 '20200927' '20200929' '20200928' '20200930' '20201001' '20201002'
 '20201003' '20201004' '20201005' '20201006' '20201007' '20201008'
 '20201009' '20201010' '20201011' '20201012' '20201013' '20201014'
 '20201015' '20201016' '20201017' '20201018' '20201019' '20201020'
 '20201021' '20201022' '20201023' '20201024' '20201025' '20201026'
 '20201027' '20201028' '20201029' '20201031' '20201030' '20201101'
 '20201102' '20201103' '20201104' '20201105' '20201106' '20201107'
 '20201108' '20201110' '20201109' '20201111' '20201112' '20201113'
 '20201114' '20201115' '20201116' '20201117' '20201118' '20201119'
 '20201120' '20201121' '20201122']

['7' '132' '39' ... '62948' '63927' '93654']

[13 19]

[10  7  2  5  1  6  3]

[501 601 201 107 210 104 306 606 108 402 307 406 604 305 508 211 302 301
 304 401 607 505 603 205 403 203 506 206 605 503 502 602 509 208 303 106
 209 202 212 610 308 207 504 215 213 204 109 101 404 102 405 103 507 105
 609 214 608]

['2' '1' '3' '{' ' ']

['대전광역시 중구 목동(행정:목동) 360' '대전광역시 중구 대흥동(대흥동) 499-1' nan ...
 '충청남도 금산군 금산읍 상리(행정:금산읍) 180-7' '세종특별자치시 세종시 도담동(행정:도담동) 642'
 '대전광역시 동구 가양동(가양1동) 286-4']

[127.40927    127.421295   127.40466276 ... 127.264178   127.44611243
 127.17338184]

[36.33301    36.325575   36.34168467 ... 36.513964   36.33970921
 36.84199059]

['Y' nan 'N' ' ']

[1.57780441e+09 1.57780449e+09 1.57780444e+09 ... 1.60597359e+09
 1.60597397e+09 1.60597149e+09]

In [11]:
'''Memory reduce'''
start_memory = npa2020.memory_usage().sum()

npa2020['HPPN_OLD_ADDR'].fillna(0, inplace=True)
npa2020.drop('SME_EVT_YN', axis=1, inplace=True)
npa2020.dropna(inplace=True)

npa2020['HPPN_X'] = npa2020['HPPN_X'].astype(np.float32)
npa2020['HPPN_Y'] = npa2020['HPPN_Y'].astype(np.float32)
npa2020['RECV_CPLT_DM'] = npa2020['RECV_CPLT_DM'].astype(np.uint32)
npa2020['NPA_CL'] = npa2020['NPA_CL'].astype(np.uint8)
npa2020['EVT_STAT_CD'] = npa2020['EVT_STAT_CD'].astype(np.uint8)
npa2020['EVT_CL_CD'] = npa2020['EVT_CL_CD'].astype(np.uint16) 
npa2020.loc[npa2020['RPTER_SEX']=='{', 'RPTER_SEX'] = 3
npa2020.loc[npa2020['RPTER_SEX']==' ', 'RPTER_SEX'] = 3
npa2020['RPTER_SEX'].fillna(3, inplace=True)
npa2020['RPTER_SEX'] = npa2020['RPTER_SEX'].astype(np.uint8)


end_memory = npa2020.memory_usage().sum()
print(f"Memory usage of dataframe after reduction {end_memory} MB")
print(f"Reduced by {100 * (start_memory - end_memory) / start_memory} % ")

Memory usage of dataframe after reduction 52752959 MB
Reduced by 49.122193438626 %

In [12]:
npa2020 = npa2020[[list(npa2020.columns)[-1]] + list(npa2020.columns)[2:-1]]

In [13]:
npa2020.isnull().sum()

RECV_CPLT_DM     0
NPA_CL           0
EVT_STAT_CD      0
EVT_CL_CD        0
RPTER_SEX        0
HPPN_OLD_ADDR    0
HPPN_X           0
HPPN_Y           0
dtype: int64

In [14]:
npa_voice = npa2020[npa2020['EVT_CL_CD'].isin(VOICE_CATEGORY)]
npa_acc = npa2020[npa2020['EVT_CL_CD'].isin(ACC_CATEGORY)]

In [15]:
kp_concat = pd.concat([kp2020, kp2021], ignore_index = True)
kp_concat

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN
...,...,...,...,...,...,...,...,...,...,...
2671132,대전청,23/01/12 11:23:09.000000000,13,10,104,1.0,대전광역시 유성구 봉명동 (행정:원신흥동 ) 1016-7,127.344600,36.352272,NaN
2671133,충남청,23/01/16 11:59:47.000000000,19,10,307,2.0,충청남도 서산시 음암면 부장리(음암면 ) 560-4,126.514047,36.785626,NaN
2671134,충남청,23/01/16 11:58:54.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2671135,충남청,23/01/14 01:00:47.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2671136,대전청,23/01/14 01:22:31.000000000,13,10,606,1.0,NaN,127.404663,36.341685,NaN

In [16]:
kp_concat.dtypes

RECV_DEPT_NM      object
RECV_CPLT_DM      object
NPA_CL             int64
EVT_STAT_CD        int64
EVT_CL_CD          int64
RPTER_SEX        float64
HPPN_PNU_ADDR     object
HPPN_X           float64
HPPN_Y           float64
SME_EVT_YN        object
dtype: object

In [17]:
kp_concat.isnull().sum()

RECV_DEPT_NM           0
RECV_CPLT_DM           0
NPA_CL                 0
EVT_STAT_CD            0
EVT_CL_CD              0
RPTER_SEX          26313
HPPN_PNU_ADDR    1101366
HPPN_X            711165
HPPN_Y            711165
SME_EVT_YN       2142758
dtype: int64

In [18]:
for colum in kp_concat.columns:
    print(kp_concat[colum].unique(), end='\n\n')

['충남청' '대전청' '2지구대(충남)' '남대전지구대' '대전대덕' '대전동부' '대전파출소' '대전역지구대' '대전중부'
 '대전둔산' '대전서부' '서대전지구대' '대전유성' '세종로파출소' '세종' '세종청' '대전유성서' '대전동부서' '대전둔산서'
 '세종서' '대전대덕서' '대전중부서' '대전서부서' '세종남부서' '세종북부서' '세종대왕파출소']

['20/12/01 01:43:07.000000000' '20/12/01 02:05:04.000000000'
 '20/12/01 02:06:52.000000000' ... '23/01/16 11:58:54.000000000'
 '23/01/14 01:00:47.000000000' '23/01/14 01:22:31.000000000']

[19 13 31 21 18  8 11 16 20 15 14  9 23 22 10 17 24 12]

[10  7  5  8  3  1  2  6  9]

[305 601 606 401 301 107 406 402 307 201 604 210 501 303 211 304 208 403
 302 503 206 104 508 607 506 502 504 306 505 602 106 202 205 209 215 207
 509 507 108 212 109 603 610 213 204 308 609 214 105 405 216 102 203 101
 605 404 103]

[ 1.  3.  2. nan]

['충청남도 보령시 궁촌동(행정:대천4동) 369' nan '충청남도 보령시 천북면 하만리 628-10 ' ...
 '충청남도 보령시 대천동 (행정:대천2동 ) 49-17' '충청남도 보령시 주교면 주교리(행정:주교면 ) 673-2'
 '충청남도 서산시 음암면 부장리(음암면 ) 560-4']

[126.59834536 127.40466276 126.52498    ... 126.678755   126.559136
 126.51404703]

[36.34153743 36.34168467 36.47439    ... 36.76983773 36.390609
 36.7856261 ]

['Y' nan 'N']

In [19]:
'''Memory reduce'''
start_memory = kp_concat.memory_usage().sum()

kp_concat['HPPN_PNU_ADDR'].fillna(0, inplace=True)
kp_concat.drop('SME_EVT_YN', axis=1, inplace=True)
kp_concat.dropna(inplace=True)

# kp_concat['RECV_CPLT_DM'].apply(lambda x : datetime.strptime(x.split('.')[0],"%d/%m/%y %H:%M:%S").timestamp())
kp_concat['HPPN_X'] = kp_concat['HPPN_X'].astype(np.float32)
kp_concat['HPPN_Y'] = kp_concat['HPPN_Y'].astype(np.float32)
kp_concat['RECV_CPLT_DM'] = kp_concat['RECV_CPLT_DM'].apply(lambda x : x.split('.')[0])
kp_concat['RECV_CPLT_DM'] = kp_concat['RECV_CPLT_DM'].apply(lambda x : datetime.strptime(x,"%y/%m/%d %H:%M:%S").timestamp())
kp_concat['RECV_CPLT_DM'] = kp_concat['RECV_CPLT_DM'].astype(np.uint32)
kp_concat['NPA_CL'] = kp_concat['NPA_CL'].astype(np.uint8)
kp_concat['EVT_STAT_CD'] = kp_concat['EVT_STAT_CD'].astype(np.uint8)
kp_concat['EVT_CL_CD'] = kp_concat['EVT_CL_CD'].astype(np.uint16) 
kp_concat['RPTER_SEX'].fillna(3.0, inplace=True)
kp_concat['RPTER_SEX'] = kp_concat['RPTER_SEX'].astype(np.uint8)

end_memory = kp_concat.memory_usage().sum()
print(f"Memory usage of dataframe after reduction {end_memory} MB")
print(f"Reduced by {100 * (start_memory - end_memory) / start_memory} % ")

Memory usage of dataframe after reduction 80331669 MB
Reduced by 62.407571718667086 %

In [20]:
kp_concat.dtypes

RECV_DEPT_NM      object
RECV_CPLT_DM      uint32
NPA_CL             uint8
EVT_STAT_CD        uint8
EVT_CL_CD         uint16
RPTER_SEX          uint8
HPPN_PNU_ADDR     object
HPPN_X           float32
HPPN_Y           float32
dtype: object

In [21]:
kp_concat.isnull().sum()

RECV_DEPT_NM     0
RECV_CPLT_DM     0
NPA_CL           0
EVT_STAT_CD      0
EVT_CL_CD        0
RPTER_SEX        0
HPPN_PNU_ADDR    0
HPPN_X           0
HPPN_Y           0
dtype: int64

In [22]:
kp_concat['RECV_CPLT_DM']

0          1606754587
1          1606755904
2          1606756012
3          1606757845
4          1606778270
              ...
2671130    1673872077
2671131    1673873270
2671132    1673490189
2671133    1673837987
2671136    1673626951
Name: RECV_CPLT_DM, Length: 1959309, dtype: uint32

In [23]:
kp_concat['EVT_CL_CD'].unique()

array([305, 601, 606, 401, 301, 107, 406, 402, 307, 201, 604, 210, 501,
       303, 211, 304, 208, 302, 503, 206, 104, 403, 508, 607, 506, 502,
       504, 306, 505, 602, 106, 202, 205, 209, 215, 207, 509, 507, 108,
       212, 109, 603, 610, 213, 204, 308, 609, 214, 105, 216, 102, 203,
       101, 605, 405, 404, 103], dtype=uint16)

In [24]:
kp_voice = kp_concat[kp_concat['EVT_CL_CD'].isin(VOICE_CATEGORY)]
kp_acc = kp_concat[kp_concat['EVT_CL_CD'].isin(ACC_CATEGORY)]
#004교통, 215보이스피싱 401/402/403교통사고/불편/위반 406음주운전

In [25]:
npa_voice

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y
3221,1577945368,13,10,215,2,0,127.404663,36.341686
3408,1577936031,13,10,215,1,대전광역시 동구 용전동(행정:용전동) 220,127.430176,36.336494
3589,1577938924,13,10,215,1,대전광역시 서구 도안동(행정:가수원동) 1564,127.348045,36.310257
3623,1577929591,13,10,215,2,대전광역시 유성구 대정동(행정:진잠동) 1-4,127.336372,36.317772
3637,1577939500,13,10,215,1,대전광역시 서구 도안동(행정:가수원동) 1564,127.349464,36.310192
...,...,...,...,...,...,...,...,...
1177819,1605841043,19,10,215,1,충청남도 보령시 주포면 보령리(행정:주포면) 255,126.588440,36.415474
1177845,1605847262,19,10,215,2,충청남도 아산시 신창면 읍내리(신창면) 646(V 순천향대학교),126.933052,36.770741
1177909,1605851118,13,10,215,2,대전광역시 대덕구 덕암동(행정:덕암동) 14-4,127.427444,36.442074
1177918,1605839472,19,10,215,2,충청남도 보령시 신흑동(행정:대천5동) 1983,126.516426,36.306057
1177944,1605847599,19,10,215,2,충청남도 아산시 탕정면 매곡리(행정:탕정면) 303-2,127.085289,36.785610

In [26]:
npa_acc

,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y
38,1577806360,13,10,402,1,대전광역시 서구 탄방동(탄방동) 1447-1,127.386345,36.346855
41,1577806532,13,10,406,1,대전광역시 유성구 궁동(행정:온천2동) 423-8,127.349991,36.360798
54,1577805695,13,10,401,1,대전광역시 유성구 봉명동(행정:온천1동) 541-26,127.348625,36.353828
66,1577806981,13,10,401,1,대전광역시 중구 오류동(행정:오류동) 187-27,127.405052,36.328571
117,1577871815,13,10,401,3,대전광역시 동구 가양동 630,127.445778,36.345501
...,...,...,...,...,...,...,...,...
1178083,1605972007,13,7,406,1,대전광역시 중구 오류동(행정:오류동) 175-2,127.404541,36.325218
1178086,1605973208,13,5,401,1,대전광역시 동구 신흥동(행정:신인동) 212,127.446091,36.320141
1178143,1605974239,19,5,406,3,충청남도 천안시 서북구 불당동(행정:불당동) 1540,127.107620,36.813774
1178173,1605973073,13,5,401,1,대전광역시 동구 신흥동(행정:신인동) 212,127.446091,36.320141
1178234,1605971722,19,7,406,1,충청남도 천안시 동남구 안서동(신안동) 산16-5,127.173386,36.841991

In [27]:
kp_voice

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y
333,충남청,1606802798,19,10,215,1,충청남도 아산시 온천동(온양1동) 1556(신학산텔레콤),127.001701,36.786900
360,충남청,1606802000,19,10,215,2,충청남도 공주시 우성면 동대리(행정:우성면) 173,127.052116,36.470196
367,충남청,1606788943,19,10,215,2,충청남도 공주시 반포면 공암리(행정:반포면),127.251167,36.395767
372,충남청,1606795689,19,10,215,1,충청남도 아산시 음봉면 삼거리(행정:음봉면) 203-3,127.012489,36.849075
375,충남청,1606798807,19,10,215,1,충청남도 천안시 동남구 다가동(일봉동) 354-1(농협중앙회봉명지점),127.140701,36.802345
...,...,...,...,...,...,...,...,...,...
2669357,대전청,1673518354,22,10,215,1,대전광역시 서구 둔산동 (행정:둔산1동 ) 1388,127.392815,36.354828
2669415,충남청,1673868439,19,10,215,2,충청남도 천안시 서북구 두정동 (행정:부성2동 ) 526-2,127.131950,36.828110
2669430,충남청,1673485091,31,10,215,1,세종특별자치시 세종시 집현동 (행정:반곡동 ) 0,127.324814,36.490017
2670687,대전청,1674026222,13,10,215,2,대전광역시 대덕구 신일동 (행정:목상동 ) 1687-6,127.406898,36.437927
2670993,충남청,1673926357,19,10,215,2,충청남도 아산시 배방읍 장재리(배방읍 ) 1767,127.107872,36.797009

In [28]:
kp_acc

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y
4,충남청,1606778270,19,10,401,2,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137161,36.826717
7,대전청,1606760666,13,10,406,1,대전광역시 유성구 봉명동(행정:온천1동) 575,127.341553,36.353695
8,충남청,1606775838,19,10,402,1,충청남도 천안시 서북구 성환읍 성월리(행정:성환읍) 150,127.136139,36.917900
9,대전청,1606774124,13,10,401,1,대전광역시 중구 석교동(석교동) 85-14,127.447548,36.306725
10,대전청,1606774160,13,10,401,2,대전광역시 중구 석교동(행정:석교동) 88-11,127.447174,36.306694
...,...,...,...,...,...,...,...,...,...
2671071,대전청,1673780499,13,10,401,1,대전 서구 괴정동 88-6,127.384285,36.334507
2671079,충남청,1673872016,19,10,401,1,충청남도 태안군 근흥면 두야리(근흥면 ) 246-2,126.262390,36.751469
2671083,충남청,1673625768,19,10,403,2,충청남도 천안시 동남구 다가동 (일봉동 ) 61-35,127.147675,36.789124
2671096,대전청,1673685338,13,10,401,1,대전광역시 대덕구 신탄진동 (행정:신탄진동 ) 129-7,127.433784,36.450726
2671112,대전청,1673712800,13,10,401,1,대전광역시 대덕구 평촌동 (행정:덕암동 ) 346,127.428284,36.425404

In [29]:
npa_voice.to_csv('./data/npa_voice.csv', index=False)
npa_acc.to_csv('./data/npa_acc.csv', index=False)
kp_voice.to_csv('./data/kp_voice.csv', index=False)
kp_acc.to_csv('./data/kp_acc.csv', index=False)